### ISSUE TITLE
special numbers not represented properly

### ISSUE THREAD

**Issue by chaimleib** [OriHoch/python-hebrew-numbers#1]
To avoid certain spelled-out words, alternate representations are used. For example:

``` yaml
15: 'ט״ו'
16: 'ט״ז'
#...
270: 'ע״ר'
272: 'ער״ב'
298: 'רח״צ'
#...
```

If you add in a YAML file with these alternate representations, you could first do a lookup on the YAML. If it's not in the list of specials, you can generate the letters as before.

**Comment by OriHoch** [comment]
the current algorithm is quite stupid (or maybe it's smart..?)

it just adds up the values of the letters, regardless of what order they are in

In [2]: gematria_to_int(u'רח"צ')
Out[2]: 298

In [3]: gematria_to_int(u'אברקדברא')
Out[3]: 510

anyway, thanks for the feedback :) I'd love to hear if you are using this library in your project..

**Comment by OriHoch** [comment]
oh, now I understand, you thought my library converts numbers to letters?

no, it doesn't, it only converts letters to numbers..

you are welcome to add that feature and I will gladly merge it

**Comment by OriHoch** [comment]
I updated the documentation to make it clearer - https://github.com/OriHoch/python-hebrew-numbers/blob/master/README.md

**Comment by chaimleib** [comment]
Aha. I think it would make sense to have a platform-independent file in a separate repo containing the special cases. That would simplify the issue for lots of developers. I'll see about creating that later today, B"N.

**Comment by chaimleib** [comment]
Here you go! https://github.com/chaimleib/hebrew-special-numbers

**Comment by OriHoch** [comment]
thanks, looks good :+1: 

I linked to your project from our readme
