### ISSUE TITLE
int_to_gematria should work when installing from pip

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/python-hebrew-numbers#8]
### reproduction steps
```
$ python --version
Python 2.7.12+  -- (it reproduces for Python 3.5.3 as well)
$ pip install --upgrade https://github.com/OriHoch/python-hebrew-numbers/archive/master.zip
$ python
>>> from hebrew_numbers import int_to_gematria
```

#### expected
* should work

#### actual
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ori/tmp/venv/local/lib/python2.7/site-packages/hebrew_numbers/__init__.py", line 8, in <module>
    specialnumbers = yaml.safe_load(io.open(DATA_PATH, encoding='utf8'))
IOError: [Errno 2] No such file or directory: '/home/ori/tmp/venv/local/lib/python2.7/site-packages/hebrew-special-numbers/styles/default.yml'
```

**Comment by OriHoch** [comment]
still reproduces for me

I tried pip install locally as well

```
python-hebrew-numbers$ pip install -e .
python-hebrew-numbers$ python
>>> from hebrew_numbers import int_to_gematria
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ori/python-hebrew-numbers/hebrew_numbers/__init__.py", line 9, in <module>
    specialnumbers = yaml.safe_load(io.open(DATA_PATH, encoding='utf8'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ori/python-hebrew-numbers/hebrew-special-numbers/styles/default.yml'
```

**Comment by ninjaaron** [comment]
hm... This should definitely work. The one thing I can think is that maybe you didn't initialize and pull down the hebrew-special-numbers locally with `git submodule init` and `git submodule update`? I tested it and reproduced the error in a repo without an initialized submodule, and it worked after I ran these commands. (you can also clone a fresh repo with `git clone --recurse-submodules` and get the same effect)

You have to do this on the git-repo where you build the package, but it should be pulled into the python package when it is built. (i.e. people installing with pip don't have to worry about submodules).

**Comment by OriHoch** [comment]
I'm trying to install the package as a user, following the usage guide in the [README](https://github.com/OriHoch/python-hebrew-numbers#usage)

feel free to update the README accordingly (e.g. if it requires to run from the repo - it's fine, just say it on the README)

**Comment by ninjaaron** [comment]
will do!

**Comment by ninjaaron** [comment]
Oh, wow! downloading a zip from github doesn't include the files in the submodule. That is surprising, and by surprising, I mean "bad." I'll update the docs right away.

**Comment by ninjaaron** [comment]
Ok. I updated the docs (just directly in master). You can close the issue once you've confirmed the new directions work on your system. Sorry about all the hassle that has been involved with the addition of this feature!

**Comment by OriHoch** [comment]
looks good, thanks!
